/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-04-01 13:45:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>微牌后台管理系统登陆</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Modern Responsive web template, Bootstrap Web Templates, Flat Web Templates,\r\n");
      out.write("\t\t\t Andriod Compatible web template,Smartphone Compatible web template, free webdesigns for Nokia, Samsung,\r\n");
      out.write("\t\t\t  LG, SonyErricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\t\taddEventListener(\"load\", function() {\r\n");
      out.write("\t\t\t\tsetTimeout(hideURLbar, 0);\r\n");
      out.write("\t\t\t}, false);\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction hideURLbar() {\r\n");
      out.write("\t\t\t\twindow.scrollTo(0, 1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t$.ajax({\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t   type: \"POST\",\r\n");
      out.write("\t\t\t   url: \"");
      out.print(basePath);
      out.write("controller/manager/login\",\r\n");
      out.write("\t\t\t   data: \"username=\"+$(\"#username\").val()+\"&password=\"+$(\"#password\").val(),\r\n");
      out.write("\t\t\t   success: function data(data){\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t\t\t\t\tvar param = eval('('+data+')');\r\n");
      out.write("\t\t\t\t\t\tif(param.mess == 0){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\twindow.location = \"");
      out.print(basePath);
      out.write("view/index.jsp\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"登录失败，账户或密码有误\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<!----webfonts--->\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.useso.com/css?family=Roboto:400,100,300,500,700,900'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<!---//webfonts--->\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/sysOperate/users.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"login\">\r\n");
      out.write("\t<div class=\"login-logo\">\r\n");
      out.write("\t\t<a href=\"index.html\"><img src=\"images/logo.png\" alt=\"\" /> </a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"app-cam\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"text\" value=\"用户名\" id=\"username\"\r\n");
      out.write("\t\t\t\tonfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\tonblur=\"if (this.value == '') {this.value = '用户名';}\"> &nbsp;\r\n");
      out.write("\t\t\t<input type=\"password\" value=\"password\" id=\"password\"\r\n");
      out.write("\t\t\t\tonfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Password';}\"> <!-- <input\r\n");
      out.write("\t\t\t\ttype=\"radio\" name=\"role\" value=\"admin\" /> <label> 管理员 </label> <input\r\n");
      out.write("\t\t\t\ttype=\"radio\" name=\"role\" value=\"agent\" /> <label> 代理商 </label> <input\r\n");
      out.write("\t\t\t\ttype=\"radio\" name=\"role\" value=\"retailer\" /> <label> 零售商 </label> -->\r\n");
      out.write("\t\t\t<div class=\"button\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" onclick=\"login()\" value=\"登陆\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"new\">\r\n");
      out.write("\t\t\t\t<li class=\"new_left\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">修改密码</a>\r\n");
      out.write("\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t<li class=\"new_right\">\r\n");
      out.write("\t\t\t\t\t<p class=\"sign\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"register.html\"> 注册</a>\r\n");
      out.write("\t\t\t\t\t</p></li>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"copy_layout login\">\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tCopyright &copy; 2016.Company name All rights reserved. <a\r\n");
      out.write("\t\t\t\ttarget=\"_blank\">微牌官方</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
